### ISSUE TITLE
Add Treehouse Courses to be completed

### ISSUE THREAD

**Issue by EMR-1** [EMR-1/Treehouse#2]
## TODO

* Courses left in CodeLouisville FrontEnd*

- [ ] CSS Layout Basics
- [ ] JavaScript Loops, Arrays and Objects
- [ ] CSS Selectors
- [ ] jQuery Basics
- [ ] CSS Flexbot Layout
- [ ] JavaScript and the DOM
- [ ] Responsive Layouts
- [ ] AJAX Basics
- [ ] Bootstrap 4 Basics
- [ ] Accessibility
- [ ] Website Optimization
- [ ] Introduction to Design Patterns
- [ ] Angular Basics (optional)
- [ ] Sass Basics (optional)

😄 

@brian.luerman@gmail.com
